# This Ansible playbook installs Kubernetes on all targeted Ubuntu hosts with elevated privileges (become: yes).
# It adds the Kubernetes GPG key and repository, installs kubeadm, kubelet, and kubectl, updates the package cache, 
# and disables swap for proper Kubernetes operation

- name: Install Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Add Kubernetes GPG key
      shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

    - name: Add Kubernetes repository
      shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Disable swap
      shell: swapoff -a
